library(tidyverse) # to use with na_drop

###READ!!!
# The data were extracted with ArcGIS from the datos abiertos maps, found in the 
#folder SIG_PECIG
#       -> automated: read soil data from departments, read PECIG polygons, clip departments by polygon -> create spatialdf.
# The extracted data are found in the files Suelos_Nucleo_x 
#       -> a similar df should be used as input in the soiltxt algorithm
# The input for the following analysis are DBR_Suelos_xxx (DBR .. data base for R), 
#which have additional taxonomic distances columns, estimated "manually".
#     -> these should be generated by the SOiltxt basic function.

# Set working directory to "Analisis" folder
df_n1_guaviare <- read.csv("./Datos/DB_Diversidad_suelos/DBR_Suelos_Nucleo1_Guaviare.csv", header = TRUE)
df_n1_meta <- read.csv("./Datos/DB_Diversidad_suelos/DBR_Suelos_Nucleo1_Meta.csv", header = TRUE)
df_n1_vichada <- read.csv("./Datos/DB_Diversidad_suelos/DBR_Suelos_Nucleo1_Vichada.csv", header = TRUE)
df_n2_caqueta <- read.csv("./Datos/DB_Diversidad_suelos/DBR_Suelos_Nucleo2_Caqueta.csv", header = TRUE)

# Correct name of first variable... due to error in export from ArcGIS name
names(df_n1_guaviare)[1] <- "OBJECTID"
names(df_n1_meta)[1] <- "OBJECTID"
names(df_n1_vichada)[1] <- "OBJECTID"
names(df_n2_caqueta)[1] <- "OBJECTID"


# Short version
df_n1_guaviare <- df_n1_guaviare[,c("OBJECTID","UCS_F","UCS_TIPO", "DEPTO","NUM_SUELOS","NIVEL_TAXO", "DIST_11","DIST_12",
                                  "DIST_13","DIST_14","DIST_15","DIST_16","DIST_21","DIST_22","DIST_23",
                                  "DIST_24","DIST_25","DIST_26","DIST_31","DIST_32","DIST_33","DIST_34",
                                  "DIST_35","DIST_36","DIST_41","DIST_42", "DIST_43","DIST_44","DIST_45",
                                  "DIST_46","DIST_51","DIST_52","DIST_53","DIST_54","DIST_55","DIST_56",
                                  "DIST_61","DIST_62","DIST_63","DIST_64","DIST_65","DIST_66","P1","P2","P3",
                                  "P4","P5","P6")]

df_n1_meta <- df_n1_meta[,c("OBJECTID","UCS_F","UCS_TIPO", "DEPTO","NUM_SUELOS","NIVEL_TAXO", "DIST_11","DIST_12",
                 "DIST_13","DIST_14","DIST_15","DIST_16","DIST_21","DIST_22","DIST_23",
                 "DIST_24","DIST_25","DIST_26","DIST_31","DIST_32","DIST_33","DIST_34",
                 "DIST_35","DIST_36","DIST_41","DIST_42", "DIST_43","DIST_44","DIST_45",
                 "DIST_46","DIST_51","DIST_52","DIST_53","DIST_54","DIST_55","DIST_56",
                 "DIST_61","DIST_62","DIST_63","DIST_64","DIST_65","DIST_66","P1","P2","P3",
                 "P4","P5","P6")]

df_n1_vichada <- df_n1_vichada[,c("OBJECTID","UCS_F","UCS_TIPO", "DEPTO","NUM_SUELOS","NIVEL_TAXO", "DIST_11","DIST_12",
                              "DIST_13","DIST_14","DIST_15","DIST_16","DIST_17","DIST_21","DIST_22","DIST_23",
                              "DIST_24","DIST_25","DIST_26","DIST_27","DIST_31","DIST_32","DIST_33","DIST_34",
                              "DIST_35","DIST_36","DIST_37","DIST_41","DIST_42", "DIST_43","DIST_44","DIST_45",
                              "DIST_46","DIST_47","DIST_51","DIST_52","DIST_53","DIST_54","DIST_55","DIST_56",
                              "DIST_57","DIST_61","DIST_62","DIST_63","DIST_64","DIST_65","DIST_66","DIST_67",
                              "DIST_71","DIST_72","DIST_73","DIST_74","DIST_75","DIST_76","DIST_77","P1","P2",
                              "P3","P4","P5","P6","P7")]

df_n2_caqueta <- df_n2_caqueta[,c("OBJECTID","UCS_F","UCS_TIPO", "DEPTO","NUM_SUELOS","NIVEL_TAXO", "DIST_11","DIST_12",
                                 "DIST_13","DIST_14","DIST_15","DIST_16","DIST_21","DIST_22","DIST_23",
                                 "DIST_24","DIST_25","DIST_26","DIST_31","DIST_32","DIST_33","DIST_34",
                                 "DIST_35","DIST_36","DIST_41","DIST_42", "DIST_43","DIST_44","DIST_45",
                                 "DIST_46","DIST_51","DIST_52","DIST_53","DIST_54","DIST_55","DIST_56",
                                 "DIST_61","DIST_62","DIST_63","DIST_64","DIST_65","DIST_66","P1","P2","P3",
                                 "P4","P5","P6")]

#Remove error information
df_n1_guaviare <- drop_na(df_n1_guaviare, NIVEL_TAXO)
df_n1_guaviare <- drop_na(df_n1_guaviare, UCS_TIPO)

df_n1_meta <- drop_na(df_n1_meta, NIVEL_TAXO)
df_n1_meta <- drop_na(df_n1_meta, UCS_TIPO)

df_n1_vichada <- drop_na(df_n1_vichada, NIVEL_TAXO)
df_n1_vichada <- drop_na(df_n1_vichada, UCS_TIPO)

df_n2_caqueta <- drop_na(df_n2_caqueta, NIVEL_TAXO)
df_n2_caqueta <- drop_na(df_n2_caqueta, UCS_TIPO)


# Extract information for index calculations: distances and proportions
dist_n1guav <- df_n1_guaviare[,7:42]
p_n1guav <- df_n1_guaviare[,43:48]
str(dist_n1guav)
str(p_n1guav)

dist_n1meta <- df_n1_meta[,7:42]
p_n1meta <- df_n1_meta[,43:48]
str(dist_n1meta)
str(p_n1meta)

dist_n1vich <- df_n1_vichada[,7:55]
p_n1vich <- df_n1_vichada[,56:62]
str(dist_n1vich)
str(p_n1vich)

dist_n2caqu <- df_n2_caqueta[,7:42]
p_n2caqu <- df_n2_caqueta[,43:48]
str(dist_n2caqu)
str(p_n2caqu)

# replace NA for 0 in df to avoid error
baseR.replace      <- function(x) { replace(x, is.na(x), 0) } # function to replace NA for 0

dist0_n1guav <- baseR.replace(dist_n1guav) 
dist0_n1meta <- baseR.replace(dist_n1meta) 
dist0_n1vich <- baseR.replace(dist_n1vich) 
dist0_n2caqu <- baseR.replace(dist_n2caqu) 

summary(is.na(dist0_n2caqu))


# Create function to calculate diversity index with summation
# Function for six soils
fun_rao6 <- function(x,y){
  (x[1]*y[1]*y[1])+ (x[2]*y[1]*y[2])+(x[3]*y[1]*y[3])+(x[4]*y[1]*y[4])+(x[5]*y[1]*y[5])+(x[6]*y[1]*y[6])+
    (x[7]*y[2]*y[1])+(x[8]*y[2]*y[2])+(x[9]*y[2]*y[3])+(x[10]*y[2]*y[4])+(x[11]*y[2]*y[5])+(x[12]*y[2]*y[6])+
    (x[13]*y[3]*y[1])+(x[14]*y[3]*y[2])+(x[15]*y[3]*y[3])+(x[16]*y[3]*y[4])+(x[17]*y[3]*y[5])+(x[18]*y[3]*y[6])+
    (x[19]*y[4]*y[1])+(x[20]*y[4]*y[2])+(x[21]*y[4]*y[3])+(x[22]*y[4]*y[4])+(x[23]*y[4]*y[5])+(x[24]*y[4]*y[6])+
    (x[25]*y[5]*y[1])+(x[26]*y[5]*y[2])+(x[27]*y[5]*y[3])+(x[28]*y[5]*y[4])+(x[29]*y[5]*y[5])+(x[30]*y[5]*y[6])+
    (x[31]*y[6]*y[1])+(x[32]*y[6]*y[2])+(x[33]*y[6]*y[3])+(x[34]*y[6]*y[4])+(x[35]*y[6]*y[5])+(x[36]*y[6]*y[6])
}

#Function for seven soils
fun_rao7 <- function(x,y){
  (x[1]*y[1]*y[1])+ (x[2]*y[1]*y[2])+(x[3]*y[1]*y[3])+(x[4]*y[1]*y[4])+(x[5]*y[1]*y[5])+(x[6]*y[1]*y[6])+(x[7]*y[1]*y[7])+
    (x[8]*y[2]*y[1])+(x[9]*y[2]*y[2])+(x[10]*y[2]*y[3])+(x[11]*y[2]*y[4])+(x[12]*y[2]*y[5])+(x[13]*y[2]*y[6])+(x[14]*y[2]*y[7])+
    (x[15]*y[3]*y[1])+(x[16]*y[3]*y[2])+(x[17]*y[3]*y[3])+(x[18]*y[3]*y[4])+(x[19]*y[3]*y[5])+(x[20]*y[3]*y[6])+ (x[21]*y[3]*y[7])+
    (x[22]*y[4]*y[1])+(x[23]*y[4]*y[2])+(x[24]*y[4]*y[3])+(x[25]*y[4]*y[4])+(x[26]*y[4]*y[5])+(x[27]*y[4]*y[6])+(x[28]*y[4]*y[7])+
    (x[29]*y[5]*y[1])+(x[30]*y[5]*y[2])+(x[31]*y[5]*y[3])+(x[32]*y[5]*y[4])+(x[33]*y[5]*y[5])+(x[34]*y[5]*y[6])+(x[35]*y[5]*y[7])+
    (x[36]*y[6]*y[1])+(x[37]*y[6]*y[2])+(x[38]*y[6]*y[3])+(x[39]*y[6]*y[4])+(x[40]*y[6]*y[5])+(x[41]*y[6]*y[6])+(x[42]*y[6]*y[7])+
    (x[43]*y[7]*y[1])+(x[44]*y[7]*y[2])+(x[45]*y[7]*y[3])+(x[46]*y[7]*y[4])+(x[47]*y[7]*y[5])+(x[48]*y[7]*y[6])+(x[49]*y[7]*y[7])
}

#Pass the Rao entropy function to each row
rao_guav <- fun_rao6(dist0_n1guav,p_n1guav)
names(rao_guav) <- "RAO"
head(rao_guav,10)
plot(rao_guav)

rao_meta <- fun_rao6(dist0_n1meta,p_n1meta)
names(rao_meta) <- "RAO"
head(rao_meta,10)
plot(rao_meta)

rao_vich <- fun_rao7(dist0_n1vich,p_n1vich)
names(rao_vich) <- "RAO"
head(rao_vich,10)
plot(rao_vich)

rao_caqu <- fun_rao6(dist0_n2caqu,p_n2caqu)
names(rao_caqu) <- "RAO"
head(rao_caqu,10)
plot(rao_caqu)

# Paste columns
sdf_n1guav <- cbind(df_n1_guaviare[,1:6], rao_guav)
sdf_n1meta <- cbind(df_n1_meta[,1:6], rao_meta)
sdf_n1vich <- cbind(df_n1_vichada[,1:6], rao_vich)
sdf_n2caqu <- cbind(df_n2_caqueta[,1:6], rao_caqu)

# Compile table
df_n1 <- rbind(sdf_n1guav, sdf_n1meta, sdf_n1vich) # complilar tabla para nucleo 1
df_n1$NUCLEO <- "Nucleo 1"
sdf_n2caqu$NUCLEO <- "Nucleo 2"

df_nucleos <- rbind(df_n1, sdf_n2caqu)
df_nucleos$NUCLEO <- as.factor(df_nucleos$NUCLEO)
str(df_nucleos)


# Plotting

# Adding fonts must be done before laoding ggplot package
library(extrafont)
# font_import() # Run this one only ONCE to import all fonts to R, or anytime a new font is installed
fonttable() # specifies how the family names are called
loadfonts(device = "win") #Do every session
# loadfonts(device="postscript") # in case another device is desired

library(ggplot2)
library(gghalves)
library(cowplot)

p <- ggplot(df_nucleos, aes(y = RAO, x = NUM_SUELOS)) +
  geom_half_violin(width=1.4, alpha=0.4, color = NA, fill = "#CDC0B0", trim = FALSE, side = "l")+
  geom_boxplot(width=0.2, color="black",show.legend = FALSE,  alpha=0.4, lwd=0.2, outlier.size = 0.001)+
  geom_half_point_panel(aes(color = UCS_TIPO), alpha = 0.6, side = "r", range_scale = 0.1, size = 0.4, transformation = position_jitter())+
  scale_colour_manual(name = "Tipo de UCS", 
                      values = c("Consociacion" = "#5B9F90", "Asociacion" = "#B6B800","Complejo" = "#F0C73B",  "Disociacion" = "#E96149"),
                      breaks=c('Disociacion','Complejo','Asociacion','Consociacion'))+
  theme_bw(base_size = 9, base_family = "Comfortaa")+
  guides(color = guide_legend(override.aes = list(size = 2)))+
  labs(y = "Incertidumbre (entropía cuadratica)", x = "Numero de suelos reportados por UCS")+
  facet_grid(~ DEPTO, scales = "free")+
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face="bold", color = "#CDC5BF", size = 9),
    axis.text = element_text(size=6.5),
    axis.title= element_text(size = 7.5),
    axis.title.x = element_text(margin = margin(t = 8)),
    axis.title.y = element_text(margin = margin(r = 8)),
    axis.ticks.length.x = unit(.5, "mm"),
    axis.ticks.length.y = unit(.1, "mm"),
    axis.ticks.y=element_blank(),
    legend.title = element_text(size = 9, face = "bold"),
    legend.text = element_text(size = 7.5),
    legend.key.size = unit(0.4, "cm")
  )


ggsave("PECIG_DiversidadRAO.png", dev = "png", type = "cairo", height = 3, width = 6)


# Export new table to plot maps in GIS
write.csv(df_n1, file = "Entropia_quadratica_nucleo1.csv")
write.csv(sdf_n2caqu, file = "Entropia_quadratica_nucleo2.csv")

  

  
 
  
